/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.EndPoint.EndPoint;
import org.example.EndPoint.EndPointImpl;
import org.example.EndPoint.RateLimitedEndPoint;
import org.example.RateLimiters.LeakyBucketRateLimiter;
import org.example.RequestSimulator.RequestSimulator;

public class App {
    public static void main(String[] args) {
        if(args.length < 2) {
            System.out.println("Usage: RequestSimulator <threads> <requestsPerSecond>");
            return;
        }

        int numOfThreads = Integer.parseInt(args[0]);
        int numOfRequestPerSecond = Integer.parseInt(args[1]);
    }
}
