echo Compiling project...
call gradlew.bat build

echo Starting Server...
start /b gradlew.bat :rate-limited-api:run

echo Waiting for server...
timeout /t 5

echo Starting Simulator...
call gradlew.bat :request-simulator:run